[package]
name = "frostbit"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcore ={ version = "0.1.0", git = "https://github.com/dgtlrst/bitcore" }
iced = "0.13.1"
rand = "0.8"
tracing-subscriber = "0.3"